FROM node:20.12.0-alpine as build

WORKDIR /app
COPY frontend .

RUN npm install

RUN npm run build

FROM nginx:latest as production

WORKDIR /app
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]